server:
  connection-timeout: 5000
  port: 8082

spring:
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/photoz?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

keycloak:
  auth-server-url: http://localhost:8180/auth
  ssl-required: external
  bearer-only: true
  cors: true
  realm: keycloak-quickstart
  resource: resource-photoz
  credentials.secret: secret
#  verify-token-audience: true
#  use-resource-role-mappings: true
#  confidential-port: 0
  securityConstraints:
    - authRoles:
        - "**"
      securityCollections:
        - patterns:
            - "/*"
  policy-enforcer-config:
#    enforcement-mode: "Enforcing"
    enforcement-mode: "PERMISSIVE"
    user-managed-access: {}
    lazy-load-paths: false
#    paths:
#      - path: /album/{id}
#        methods:
#          - method: "DELETE"
#            scopes:
#              - "album:delete"
#          - method: "GET"
#            scopes:
#              - "album:view"
#      - path: /album/shares
#        enforcement-mode: "DISABLED"
#      - path: /album
#        name: "Album Resource"
#        methods:
#          - method: "POST"
#            scopes:
#              - "album:create"
#          - method: "GET"
#            scopes:
#              - "album:view"
#      - path: /profile
#      - path: /error
#        enforcement-mode: "DISABLED"
#      - path: /admin/*
#      - path: /test-client-ip
#      - path: /hello
#      - path: /api/v1/*
#        enforcement-mode: "DISABLED"

logging:
  level:
    net.waret.demo.photoz: debug
    org.keycloak: trace
