server:
  connection-timeout: 5000
  port: 8081

spring:
  devtools:
    restart:
      enabled: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:bob;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: bob
    password:
    hikari:
      auto-commit: false
  h2:
    console:
      enabled: false
  jpa:
    database: H2
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true

keycloak:
  auth-server-url: http://localhost:8180/auth
#  auth-server-url: http://keycloak.waret.net/auth
  ssl-required: external
  bearer-only: true
  cors: true
  realm: photoz
#  realm: keycloak-quickstart
  resource: photoz-restful-api
#  resource: resource-photoz
  credentials.secret: secret
#  verify-token-audience: true
#  use-resource-role-mappings: true
#  confidential-port: 0
#  securityConstraints: {}
#  securityConstraints:
#    - authRoles:
#        - "*"
#      securityCollections:
#        - patterns:
#            - /*
#  policy-enforcer-config: {}
  policy-enforcer-config:
    enforcement-mode: "PERMISSIVE"
    user-managed-access: {}
    lazy-load-paths: true
    paths:
      - name: "Album Resource"
        path: /album/{id}
        methods:
          - method: "DELETE"
            scopes:
              - "album:delete"
          - method: "GET"
            scopes:
              - "album:view"
      - name: "Album Resource"
        path: /album/shares
        enforcement-mode: "DISABLED"
      - name: "User Profile Resource"
        path: /profile
      - name: "Admin Resources"
        path: /admin/*

logging:
  level:
    net.waret.demo.photoz: debug
    org.keycloak: debug
