
server:
  connection-timeout: 5000
  port: 8081

keycloak:
  auth-server-url: http://localhost:8180/auth
  ssl-required: external
  bearer-only: true
  cors: true
  realm: keycloak-quickstart
  resource: resource-alice
  credentials.secret: secret
  securityConstraints:
    - authRoles:
        - user
      securityCollections:
        - name: protected
          patterns:
            - /api/*
    - authRoles:
        - user-premium
      securityCollections:
        - name: protected-premium
          patterns:
            - /api/premium
  policy-enforcer-config:
    enforcement-mode: "Enforcing"
    user-managed-access: {}
    lazy-load-paths: true
    paths:
      - path: /api/admin          # 通过 path 查找 Keycloak 服务器中定义的资源
        name: "Admin Resource"    # 通过 name 查找 Keycloak 服务器中定义的资源
        claimInformationPointConfig:
          claims:
            some-claim: "{request.parameter['parameter-a']}"

logging:
  level:
    net.waret.demo.alice: debug
